manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ziombo
      url-base: https://github.com/ziombo
  projects:
    - name: zmk
      remote: ziombo
      revision: master
      import: app/west.yml
  self:
    path: config
